# Generated by Django 3.0.8 on 2020-07-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
